#pragma once

enum EStat{VIE_MAX, MANA_MAX, VITESSE, FORCE, INTELLIGENCE, DISCRETION, ARMURE, REMPART, REFLEXION, GUERISON, ESTATMAX};

enum class EDegat{PHYSIQUE, MAGIQUE, BRUT};

enum class EPopo{FAIBLE, MOYENNE, FORTE, LEGENDAIRE};

enum ENiveau {INFO, ERREUR, FATAL};

enum ETexture {HERBE1, HERBE2, NEIGE1, ROCK_LICHEN1, TEXTURE_MAX};

enum class EMove{BACK, STOP, FORWARD};