#pragma once

enum EStat{VIE_MAX, MANA_MAX, VITESSE, FORCE, INTELLIGENCE, DISCRETION, ARMURE, REMPART, REFLEXION, GUERISON, ESTATMAX};

enum class EDegat{PHYSIQUE, MAGIQUE, BRUT};

enum class EPopo{FAIBLE, MOYENNE, FORTE, LEGENDAIRE};

enum ENiveau {INFO, ERREUR, FATAL};