#pragma once

enum EDegat{PHYSIQUE, MAGIQUE, BRUT};
enum EStat{VIE_MAX, MANA_MAX, VITESSE, FORCE, INTELLIGENCE, DISCRETION, ARMURE, REMPART, REFLEXION, GUERISON, ESTATMAX};
enum EPopo{FAIBLE, MOYENNE, FORTE, LEGENDAIRE};

